name: test
on:
  pull_request:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the script
        run: make test
        env:
          SECRET1: ${{ secrets.SECRET1 }}
