name: pull_request_target workflow
on:
  pull_request_target: # Use pull_request_target
    branches: [ '*' ]
jobs:
  pull_request_target:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.repo.fork == true && 'DEV' || 'PROD' }}
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run the script
        run: make test
        env:
          SECRET1: ${{ secrets.SECRET1 }}
