name: test
on:
  pull_request_target: # Use pull_request_target
    branches: [ '*' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the script
        run: make test
        env:
          SECRET1: ${{ secrets.SECRET1 }}
